### ISSUE TITLE
link not working for the inventory_file: example-1.ini or playbook_file: playbook-1.yml 

### ISSUE THREAD

**Issue by mdminhaj88** [opencrvs/opencrvs-countryconfig#52]
The example for the inventory_file and playbook_file are not available from the link provided in the openCRVS 3.3.2 page... please go through the attachments 
![link not working](https://github.com/opencrvs/opencrvs-countryconfig/assets/142885612/ce44b122-822b-4d5b-b90a-c34d38bda1be)
![not found](https://github.com/opencrvs/opencrvs-countryconfig/assets/142885612/74d95955-3d1d-43f0-83ea-ccc0472d7c70)

Is there any alternate method or reference to be followed?

**Comment by euanmillar** [comment]
Hi @mdminhaj88, sorry about this.  We are poised to release v1.4.0 and all these docs will be refreshed.
Our plan is to release this on Friday 23rd. We had hoped to release it last week but we reverted it due to some ongoing issues.  I appreciate your patience.

**Comment by euanmillar** [comment]
These docs are deprecated in 1.4.0.  Refer to the latest documentation: https://documentation.opencrvs.org/setup/3.-installation/3.3-set-up-a-server-hosted-environment
