### ISSUE TITLE
SUPER_USER_PASSWORD

### ISSUE THREAD

**Issue by mdminhaj88** [opencrvs/opencrvs-countryconfig#72]
hi,

can you throw some light on this, as it is one of the global repository secrets which is mandatory for cloud deployment.

And if the password can be shared on this platform then please share it or you can also share it on my mail : mohammed.minhaj@technoforte.co.in

PFA ss of the same

Thanks

![super_user_password](https://github.com/opencrvs/opencrvs-countryconfig/assets/142885612/a32b0369-69d6-48a7-af78-3763632c425a)

**Comment by euanmillar** [comment]
Hi @mdminhaj88, we are poised to release v1.4.0 and all these docs will be refreshed with a thorough explanation for SUPER_USER_PASSWORD. All these github secrets can be automatically created with the [`yarn environment:init`](https://github.com/opencrvs/opencrvs-countryconfig/blob/2748b0c86f42f20dd3a053610ed33b6d94593768/package.json#L23) script.  

It is used when seeding databases with initial reference data. Its for a temporary API client user that is created in the system via database migration. The [seeding action](https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/.github/workflows/seed-data.yml) then uses this user to authenticate, seed the databases via APIs then the user is deleted.
 
Our plan is to release new v1.4.0 docs on Friday.  Please hold off deploying until then when you can review entirely updated docs along with explanation videos.

I will post a link to the docs which you will need to read thoroughly on Friday and close this ticket.

**Comment by mdminhaj88** [comment]
thank you for the prompt response!

**Comment by mdminhaj88** [comment]
hey @euanmillar 

thank you for releasing the new version

tried to run the command "yarn environment:init --environment=qa" and the following 'TSError: ⨯ Unable to compile TypeScript:' error is throwing up, please throw some light.

Atached is the ss of the same

Thanks
![unable to compile typescript](https://github.com/opencrvs/opencrvs-countryconfig/assets/142885612/8e9b1f5d-21b5-416b-9edb-13d8b7242237)
